# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.5.3"

gem "rails", "~> 5.2.2", ">= 5.2.2.1"

gem "bootsnap", ">= 1.1.0", require: false
gem "google-api-client", "~> 0.11"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "puma", "~> 3.11"
gem "sidekiq"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "rspec-rails", "~> 3.8"
end

group :development do
  gem "annotate"
  gem "debase"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "rubocop"
  gem "ruby-debug-ide"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
